import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import Head from 'next/head';
import ParticlesContainer from '@/components/ParticlesContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full relative">
            <div className="w-1/2 relative">
              <Image src={profilePic} alt="alt" className="w-full h-auto" />
              <div className="absolute inset-0 flex items-center justify-center">
                <ParticlesContainer />
              </div>
            </div>
            <div className="w-1/2">
              <h1>Crafting Digital Marvels with the Power of Code and Creativity.</h1>
              <p>
              With a knack for full-stack wizardry, I specialize in bringing your ideas to life through innovative web applications. Dive into my latest projects and insightful articles, highlighting my expertise in web development and design.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
